#!/bin/sh
set -e

lb config \
  --mode debian \
  --distribution bookworm \
  --architecture amd64 \
  --binary-images iso-hybrid \
  --bootloader grub-efi \
  --archive-areas "main contrib non-free non-free-firmware" \
  --linux-packages linux-image \
  --linux-flavours amd64 \
  --firmware-binary true \
  --firmware-chroot true \
  --iso-application "RogueOS" \
  --iso-preparer "RogueOS" \
  --iso-publisher "RogueOS" \
  --bootappend-live "boot=live components quiet splash username=rogue hostname=rogueos locales=en_CA.UTF-8,en_US.UTF-8 keyboard-layouts=us timezone=America/Regina persistence persistence-label=RogueOS" \
  --grub-timeout 3 \
  --debian-installer false \
  --system live \
  --union overlay \
  --win32-loader false
