#!/usr/bin/env bash
set -euo pipefail
lb config
--mode debian
--distribution bookworm
--architectures amd64
--binary-images iso-hybrid
--debian-installer live
--linux-flavours amd64
--apt-recommends true
--apt-secure true
--mirror-bootstrap http://deb.debian.org/debian/
--mirror-binary http://deb.debian.org/debian/
--archive-areas "main contrib non-free non-free-firmware"
--bootappend-live "boot=live components quiet splash username=rogue locales=en_CA.UTF-8,en_US.UTF-8 timezone=America/Regina"
--bootloader grub-efi
--memtest none
