name: Build RogueOS ISO
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y live-build xorriso mtools
      - name: Build ISO
        run: |
          ./build.sh
      - name: Upload ISO artifact
        uses: actions/upload-artifact@v4
        with:
          name: rogueos-amd64-${{ github.run_number }}
          path: out/*.iso
